package pinpoint

import "strings"

var clientServiceTypes = []string{
	"UNKNOWN_DB",
	"MYSQL",
	"R2DBC_MYSQL",
	"MARIADB",
	"R2DBC_MARIADB",
	"MSSQL",
	"MSSQL_JDBC",
	"R2DBC_MSSQL_JDBC",
	"ORACLE",
	"R2DBC_ORACLE",
	"CUBRID",
	"NBASET",
	"INFORMIX",
	"POSTGRESQL",
	"R2DBC_POSTGRESQL",
	"CASSANDRA",
	"MONGO",
	"COUCHDB",
	"H2",
	"R2DBC_H2",
	"CLICK_HOUSE",
	"MEMCACHED",
	"ARCUS",
	"REDIS",
	"IOREDIS",
	"HTTP_CLIENT_3",
	"HTTP_CLIENT_4",
	"GOOGLE_HTTP_CLIENT_INTERNAL",
	"JDK_HTTPURLCONNECTOR",
	"JDK_HTTPCONNECTOR",
	"ASYNC_HTTP_CLIENT",
	"OK_HTTP_CLIENT",
	"HTTP_CLIENT_5",
	"JDK_HTTP_CLIENT",
	"APACHE_CXF_CLIENT",
	"APACHE_CXF_SERVICE_INVOKER",
	"APACHE_CXF_MESSAGE_SENDER",
	"APACHE_CXF_LOGGING_IN",
	"APACHE_CXF_LOGGING_OUT",
	"THRIFT_CLIENT",
	"DUBBO_CONSUMER",
	"HYSTRIX_COMMAND",
	"VERTX_HTTP_CLIENT",
	"REST_TEMPLATE",
	"NETTY",
	"SPRING_WEBFLUX_CLIENT",
	"REACTOR_NETTY_CLIENT",
	"GRPC",
	"ElasticsearchBBoss",
	"ELASTICSEARCH",
	"ENVOY_INGRESS",
	"ENVOY_EGRESS",
	"GO_HTTP_CLIENT",
	"OPENWHISK_CLIENT",
	"PHP_REMOTE_METHOD",
	"C_CPP_REMOTE_METHOD",
	"PYTHON_REMOTE_METHOD",
	"RABBITMQ",
	"ACTIVEMQ_CLIENT",
	"KAFKA_CLIENT",
	"KAFKA_STREAMS",
}

func IsClient(serviceType string) bool {
	for _, client := range clientServiceTypes {
		if strings.HasPrefix(serviceType, client) {
			return true
		}
	}
	return false
}
