name: Release test

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to release'
        required: true

jobs:
  build-images:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: ubuntu-latest
            arch: amd64
    runs-on: ${{ matrix.os }}
    outputs:
      IMAGE_TAG_NAME: ${{ steps.build-image.outputs.IMAGE_TAG_NAME }}
    steps:
      - name: test
        run: |
          echo "test"
